version: '3.8'

services:
  coco-server:
    container_name: coco-server-1  # 指定容器名称
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9390:9390"
    restart: always
    environment:
      - ENV=development
